name: CI
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
    - master

jobs:
  test:
    # Job name is Test
    name: Test
    # This job runs on macOS
    runs-on: macOS-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_13.2.1.app && /usr/bin/xcodebuild -version
      - name: Install Dependencies
        run: pod install
      - name: Build and test
        run: xcodebuild test -workspace MovieDB.xcworkspace -scheme MovieDB -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=15.0'
