name: CI

on:
  push:
    branches: [ "CapstoneProject" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      - name : Install Dependencies
        run: pod install
      - name: Build and test
        run: xcodebuild test -workspace MovieDB.xcworkspace -scheme MovieDB -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=15.0'

